import { SongSelect } from "songselect.slint";

export component AppWindow inherits Window {
    in property <[string]> songs;
    callback add-song();
    callback load-song();
    callback delete-song(int);
    callback edit-song(int);
    SongSelect {
        songs <=> root.songs;
        add-song => {
            root.add-song();
        }
        load-song => {
            root.load-song();
        }
        delete-song(index) => {
            root.delete-song(index);
        }
    }
}
