import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

component Song inherits TouchArea {
    in-out property <string> song-name;
    callback delete-song();
    HorizontalBox {
        Text {
            text: song-name;
        }

        Button {
            text: "x";
            clicked => {
                delete-song();
            }
        }
    }
}

export component SongSelect {
    callback add-song();
    callback load-song();
    callback delete-song(int);
    callback edit-song(int);
    in property <[string]> songs;
    VerticalBox {
        HorizontalBox {
            for song[i] in songs: Song {
                song-name: song;
                clicked => {
                    edit-song(i);
                }
                delete-song => {
                    delete-song(i);
                }
            }
        }

        HorizontalBox {
            alignment: center;
            Button {
                text: "Load Song";
                width: 100px;
                clicked => {
                    load-song();
                }
            }

            Button {
                text: "Add Song";
                width: 100px;
                clicked => {
                    add-song();
                }
            }
        }
    }
}
